# Generated by Django 2.1.7 on 2019-03-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20181211_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, help_text='The score of the question', verbose_name='Score'),
        ),
    ]
