# Generated by Django 2.1.7 on 2019-04-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Answer'),
        ),
    ]
