# Generated by Django 2.1.7 on 2019-04-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
    ]
