# Generated by Django 2.1.7 on 2019-04-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_response_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Score'),
        ),
    ]
