# Generated by Django 2.1.7 on 2019-04-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_auto_20190403_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='得分'),
        ),
    ]
