# Generated by Django 2.1.7 on 2019-04-03 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_answer_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '种类', 'verbose_name_plural': '种类'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('survey', 'order'), 'verbose_name': '问题', 'verbose_name_plural': '问题'},
        ),
        migrations.AlterModelOptions(
            name='response',
            options={'verbose_name': '试卷提交', 'verbose_name_plural': '试卷提交'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'verbose_name': '试卷', 'verbose_name_plural': '试卷'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='回答内容'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Question', verbose_name='问题'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.Response', verbose_name='提交'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=400, verbose_name='种类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='显示顺序'),
        ),
        migrations.AlterField(
            model_name='category',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='survey.Survey', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='survey.Category', verbose_name='问题类别'),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text="The choices field is only used if the question type\nif the question type is 'radio', 'select', or\n'select multiple' provide a comma-separated list of\noptions for this question .", null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(verbose_name='顺序'),
        ),
        migrations.AlterField(
            model_name='question',
            name='required',
            field=models.BooleanField(verbose_name='必需'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(default=1, help_text='The score of the question', verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.Survey', verbose_name='所属试卷'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('text', '多行文本'), ('short-text', '单行文本'), ('radio', '选择按钮'), ('select', '选择下拉框'), ('select-multiple', '多选'), ('select_image', '图片下拉框'), ('integer', '整数')], default='text', max_length=200, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='response',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='response',
            name='interview_uuid',
            field=models.CharField(max_length=36, verbose_name='唯一标识符'),
        ),
        migrations.AlterField(
            model_name='response',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='成绩'),
        ),
        migrations.AlterField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.Survey', verbose_name='试卷'),
        ),
        migrations.AlterField(
            model_name='response',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='response',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(verbose_name='试卷描述'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_published',
            field=models.BooleanField(verbose_name='是否已经发布'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=400, verbose_name='考试名称'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='need_logged_user',
            field=models.BooleanField(default=True, verbose_name='只有登陆的学生可以回答'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='template',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='模板'),
        ),
    ]
