# Generated by Django 2.1.7 on 2019-04-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_auto_20190403_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='只有在使用Radio，Select时候才会使用到choices字段', null=True, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='question',
            name='score',
            field=models.IntegerField(blank=True, help_text='The score of the question', null=True, verbose_name='分值'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('radio', '选择按钮'), ('select', '选择下拉框')], default='text', max_length=200, verbose_name='类型'),
        ),
    ]
